
language: cpp

sudo: required

compiler:
  - clang

#env:
#  - COMPILER=clang++-3.9

os:
  - linux

install:
  - sudo apt-get install sqlite3 libsqlite3-dev cmake
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y;
  - sudo apt-get update -qq
  - sudo apt-cache search g++
  - sudo apt-get install g++-4.9

script:
  - cmake .
  - make
  - ctest
  - ./examples/blob
  - ./examples/collate
  - ./examples/composite_key
  - ./examples/core_functions
  - ./examples/cross_join
  - ./examples/date_time
  - ./examples/distinct
  - ./examples/enum_binding
  - ./examples/foreign_key
  - ./examples/group_by
  - ./examples/in_memory
  - ./examples/index
  - ./examples/insert
  - ./examples/iteration
  - ./examples/key_value
  - ./examples/multi_table_select
  - ./examples/nullable_enum_binding
  - ./examples/private_class_members
  - ./examples/select
  - ./examples/subentities
  - ./examples/synchronous
  - ./examples/unique
  - ./examples/update
